### ISSUE TITLE
Error in Connectivity if Reserved Networks is empty

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#200] opened 2017-02-26 08:21 UTC
If Reserved Networks attribute of 'Cloud Provider' is set to empty, it's not possible to connect - 

Here's a Stacktrace

Traceback (most recent call last):
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions       File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_9_12\lib\site-packages\cloudshell\cp\openstack\domain\services\connectivity\vlan_connectivity_service.py", line 146, in set_vlan_actions
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions         logger=logger)
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions       File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_9_12\lib\site-packages\cloudshell\cp\openstack\domain\services\neutron\neutron_network_service.py", line 84, in create_and_attach_subnet_to_net
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions         cidr = self._get_unused_cidr(client=client, cp_resvd_cidrs=cp_resource_model.reserved_networks, logger=logger)
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions       File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_9_12\lib\site-packages\cloudshell\cp\openstack\domain\services\neutron\neutron_network_service.py", line 172, in _get_unused_cidr
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions         blacklist_subnets = map(lambda x: ipaddress.IPv4Network(x), blacklist_cidrs)
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions       File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_9_12\lib\site-packages\cloudshell\cp\openstack\domain\services\neutron\neutron_network_service.py", line 172, in <lambda>
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions         blacklist_subnets = map(lambda x: ipaddress.IPv4Network(x), blacklist_cidrs)
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions       File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_9_12\lib\site-packages\ipaddress.py", line 1651, in __init__
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions         self.network_address = IPv4Address(self._ip_int_from_string(addr[0]))
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions       File "C:\ProgramData\QualiSystems\venv\OpenStack_Shell_Driver_9_12\lib\site-packages\ipaddress.py", line 1265, in _ip_int_from_string
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions         raise AddressValueError('Address cannot be empty')
2017-02-26 09:41:29,121 [ERROR]: QS.OpenStack vlan_connectivity_service - set_vlan_actions     AddressValueError: Address cannot be empty

**Comment by alexazarh** [comment] 2017-02-26 08:45
duplicate of #201

**Closed** 2017-02-26 08:46 UTC
Labels: bug, in progress, P1
